<?php
/**
 * Created by PhpStorm.
 * User: ksu
 * Date: 05.03.18
 * Time: 22:23
 */

namespace app\modules\admin\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use app\modules\admin\models\About;
use yii\web\UploadedFile;


class AboutController extends BaseController {

    

    public function actionIndex()
    {
        $parent = parent::actionIndex(); // TODO: Change the autogenerated stub
        $model = new About();
        $info = $model->getModel();
        if (is_null($info)) {
            return $this->render('add-about');
        }
        return $this->render('about', ['info' => $info]);
    }

    public function actionEdit() {

        $model = About::getInfo();
        if ($model->load(Yii::$app->request->post()) && $model->save()) {

            $model->image = UploadedFile::getInstance($model, 'image');
            if ($model->upload()) {
                $model->image = $model->image->name;

                $model->save();
                Yii::$app->session->setFlash('success', 'Ok');
            }
        }
        return $this->render('edit-about',  ['model' => $model, 'titleForm' => "Edit Form"]);
    }

    public function actionAdd() {

        $model = new About();
        if ($model->load(Yii::$app->request->post())) {
            if(!$model->save())
                print_r($model->getErrors());
            Yii::$app->session->setFlash('success', 'Ok');
        }

        return $this->render('edit-about',  ['model' => $model, 'titleForm' => "Add Form"]);

    }
}