<?php
/**
 * Created by PhpStorm.
 * User: ksu
 * Date: 05.03.18
 * Time: 22:23
 */

namespace app\modules\admin\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use app\modules\admin\models\About;

class AboutController extends BaseController {

    

    public function actionIndex()
    {
        $parent = parent::actionIndex(); // TODO: Change the autogenerated stub
        $info = About::getInfo();
//        var_dump($info); die;
        return $this->render('about', ['info' => $info]);
    }

    public function actionEdit() {

        $model = new About();
//        var_dump($model->update()); die;
        if ($model->load(Yii::$app->request->post()) && $model->update()) {
            Yii::$app->session->setFlash('success', 'Ok');
        }
        return $this->render('edit-about',  ['model' => $model]);
    }
}