<?php
/**
 * Created by PhpStorm.
 * User: ksu
 * Date: 05.03.18
 * Time: 22:33
 */

namespace app\modules\admin;

use yii\filters\AccessControl;
use Yii;

class Module extends \yii\base\Module {

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['login'],
                        'roles' => ['?','@'],

                    ],

                ],
                'denyCallback' => function () {
                    if (!\Yii::$app->user->identity) {
                        return Yii::$app->response->redirect('/');
                    }
                }
            ],
        ];
    }
}